### ISSUE TITLE
Feature Request: Customizeable Folder Name instead of "User-Suppplied+URL" 

### ISSUE THREAD

**Issue by TraeF1337** [sfuhrm/radiorecorder#8]
🤔

**Comment by sfuhrm** [comment]
I am not quite sure I understand your proposal. Can you give an example?

**Comment by filimonic** [comment]
**Task: dump radio into separate MP3 files**
`"C:\Program Files\radiorecorder\radiorecorder.exe" http://somedomain/nightcore?secret -d "D:\NighCore" -r -use-songnames`

**Expected behavior:**
Save files to `D:\NighCore\001.song.mp3`

**Actual behavior:**
Creates `D:\NighCore\User-Suppplied+URL\001.song.mp3`

**Comment by sfuhrm** [comment]
@filimonic thanks for the example! The problem here is that radiorecorder can download multiple streams _simultaneously_, so with numbered files there will be collisions if two streams provide "001.song.mp3". With named files there can be collisions.

But now I see the request more to be able to overwrite the way how to store file names and to start with a minimalistic default.

**Comment by sfuhrm** [comment]
I have changed the behaviour with user-supplied URLs.
Version 1.8.3 contains the new behaviour.
Please have a look and check whether it works for you.
